# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("font: 12pt \"Yu Gothic UI\";")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BG = QtWidgets.QGraphicsView(self.centralwidget)
        self.BG.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.BG.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.692514, y2:0.676, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(62, 196, 204, 255))")
        self.BG.setObjectName("BG")
        self.BOTTOMBAR = QtWidgets.QGraphicsView(self.centralwidget)
        self.BOTTOMBAR.setGeometry(QtCore.QRect(0, 500, 801, 101))
        self.BOTTOMBAR.setStyleSheet("background-color: rgba(0, 0, 0, 150);")
        self.BOTTOMBAR.setObjectName("BOTTOMBAR")
        self.Login = QtWidgets.QPushButton(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(20, 530, 151, 41))
        self.Login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border: black 1px solid;\n"
"outline: none;\n"
"border-radius: 3px;")
        self.Login.setObjectName("Login")
        self.NickEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NickEdit.setGeometry(QtCore.QRect(180, 530, 161, 31))
        self.NickEdit.setStyleSheet("font: 10pt \"Yu Gothic UI\";")
        self.NickEdit.setText("")
        self.NickEdit.setMaxLength(16)
        self.NickEdit.setObjectName("NickEdit")
        self.IPEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.IPEdit.setGeometry(QtCore.QRect(360, 530, 141, 21))
        self.IPEdit.setStyleSheet("font: 10pt \"Yu Gothic UI\";")
        self.IPEdit.setObjectName("IPEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(520, 530, 141, 31))
        self.lineEdit.setStyleSheet("font: 10pt \"Yu Gothic UI\";")
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 781, 481))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"font: 12pt \"Yu Gothic UI\";")
        self.textBrowser.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 560, 141, 20))
        self.lineEdit_2.setStyleSheet("font: 10pt \"Yu Gothic UI\";")
        self.lineEdit_2.setMaxLength(5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Danilus Launcher"))
        self.Login.setText(_translate("MainWindow", "Login"))
        self.NickEdit.setPlaceholderText(_translate("MainWindow", "Nickname"))
        self.IPEdit.setPlaceholderText(_translate("MainWindow", "IP Address"))
        self.lineEdit.setWhatsThis(_translate("MainWindow", "Theme Name without extension"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Theme Name"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Launcher Release</span><span style=\" font-weight:600; vertical-align:super;\">v1.1</span><span style=\" font-weight:600;\">, ChangeLog:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">EN:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Created shell command executor to launch the client.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Added &quot;Port&quot; line</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">RU:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Создан процесс вызова команды для запуска клиента</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Добавлена строка &quot;Порт&quot;</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-----------------------------------------------</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Launcher Release</span><span style=\" font-weight:600; vertical-align:super;\">v1</span><span style=\" font-weight:600;\">, ChangeLog:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">EN:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Created first UI design</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">RU:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Создан первый дизайн интерфейса</p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Port"))
